# Generated by Django 5.2.4 on 2025-07-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação')),
                ('tempo_limite', models.DurationField(verbose_name='Tempo Limite')),
                ('feedback_positivo', models.CharField(max_length=200, verbose_name='Feedback Positivo')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], max_length=10, verbose_name='Tipo de Usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_positiva', models.CharField(max_length=200, verbose_name='Mensagem Positiva')),
                ('nivel_dificuldade', models.CharField(max_length=50, verbose_name='Nível de Dificuldade')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('atividades', models.ManyToManyField(to='app.atividade', verbose_name='Atividades')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='app.usuario', verbose_name='Alunos'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_responsaveis', to='app.usuario', verbose_name='Professor Responsável'),
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividades_realizadas', models.IntegerField(verbose_name='Atividades Realizadas')),
                ('media_pontos', models.FloatField(verbose_name='Média de Pontos')),
                ('ultima_atividade', models.DateField(verbose_name='Última Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório de Desempenho',
                'verbose_name_plural': 'Relatórios de Desempenho',
            },
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('conquistas', models.CharField(max_length=200, verbose_name='Conquistas')),
                ('tempo_total_focado', models.DurationField(verbose_name='Tempo Total Focado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso do Aluno',
                'verbose_name_plural': 'Progressos dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Personalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_visual', models.CharField(max_length=100, verbose_name='Tema Visual')),
                ('som_ambiente', models.CharField(max_length=100, verbose_name='Som Ambiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Personalização',
                'verbose_name_plural': 'Personalizações',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=100, verbose_name='Avatar')),
                ('nivel_atual', models.IntegerField(verbose_name='Nível Atual')),
                ('pontos_gamificacao', models.IntegerField(verbose_name='Pontos de Gamificação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('pontuacao_obtida', models.IntegerField(verbose_name='Pontuação Obtida')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atividade', verbose_name='Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=200, verbose_name='Mensagem')),
                ('data_envio', models.DateField(verbose_name='Data de Envio')),
                ('tipo_notificacao', models.CharField(choices=[('lembrete', 'Lembrete'), ('gamificacao', 'Gamificação')], max_length=20, verbose_name='Tipo de Notificação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='DispositivoIntegrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(max_length=100, verbose_name='Tipo de Dispositivo')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dispositivo Integrado',
                'verbose_name_plural': 'Dispositivos Integrados',
            },
        ),
    ]
